### ISSUE TITLE
Provide a Docker option to run the site locally on you machine

### ISSUE THREAD

**Issue by nickebbitt** [World-Wide-JUGs/GlobalWWJugs#13]
I prefer not to install/manage Ruby versions and their dependencies on my Mac and keep them safely contained in a Docker container.

If you have Docker installed on you machines then with a simple `docker-compose.yaml` file in the project

```
version: '3'

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - '4000:4000'
```

You can spin up the site locally with
```
docker-compose up
```

Without needing to install Ruby and manage it.

Note: there are various Docker images that help you do this, I picked `bretfisher/jekyll-serve` at random from a quick Google search but if open to this I can review and choose a good candidate image to provide this feature.
